### ISSUE TITLE
Cant open google sheets XLSX

### ISSUE THREAD

**Issue by dorshay6** [guyonroche/exceljs#104]
`ypeError: Cannot read property 'style' of undefined
HM-BO-2     at Object.xml (/var/node/hm-bo/node_modules/exceljs/lib/xlsx/border.js:158:26)
HM-BO-2     at utils.inherits._addBorder (/var/node/hm-bo/node_modules/exceljs/lib/xlsx/stylemanager.js:381:47)
HM-BO-2     at SAXStream.<anonymous> (/var/node/hm-bo/node_modules/exceljs/lib/xlsx/stylemanager.js:202:34)
HM-BO-2     at SAXStream.EventEmitter.emit (events.js:95:17)
HM-BO-2     at Object.me._parser.(anonymous function) [as onclosetag] (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:245:15)
HM-BO-2     at emit (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:615:33)
HM-BO-2     at emitNode (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:620:3)
HM-BO-2     at closeTag (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:861:5)
HM-BO-2     at Object.write (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:1294:29)
HM-BO-2     at SAXStream.write (/var/node/hm-bo/node_modules/exceljs/node_modules/sax/lib/sax.js:227:16)
HM-BO-2     at write (_stream_readable.js:583:24)
HM-BO-2     at flow (_stream_readable.js:592:7)
HM-BO-2     at Entry.pipeOnReadable (_stream_readable.js:624:5)
HM-BO-2     at Entry.EventEmitter.emit (events.js:92:17)
HM-BO-2     at emitReadable_ (_stream_readable.js:408:10)
HM-BO-2     at emitReadable (_stream_readable.js:404:5)
`

**Comment by crash83k** [comment]
I'm also unable to open xlsx files from Google Sheets as well. Seems the `sheets` array doesn't exist in the model when it gets to the `default` case in `createInputStream()`. 

```
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at XLSX.createInputStream.stream.on.self.parseWorksheet.then.then (/excel/node_modules/exceljs/lib/xlsx/xlsx.js:188:60)
    at tryCatcher (/excel/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/excel/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/excel/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/excel/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/excel/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/excel/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/excel/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/excel/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by erixtekila** [comment]
Me either.
I get an error

```
Désolé, impossible d'importer ce type de fichier.
Types de fichiers acceptés : csv, txt, tsv, tab, htm, html, xls, xlsx, xlsm, xlt, xltm, xltx, ods.
```
Meaning unable to open the file.

**Comment by erixtekila** [comment]
Sorry I mispelled the extension.
Disregard my comment.

**Comment by erixtekila** [comment]
Sorry I mispelled the extension.
Disregard my comment.
