### ISSUE TITLE
read property 'richText' of undefined

### ISSUE THREAD

**Issue by vfro** [guyonroche/exceljs#120]
After upgrading to Node.js v6.1.0 (from v5.7.1) the following code which previously worked fine:
```
   workbook.xlsx.writeFile("my.xlsx");
```
Causes the following error now:
```
Unhandled rejection TypeError: Cannot read property 'richText' of undefined
    at utils.inherits.write (C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xform\shared-string-xform.js:56:14)
    at C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xform\shared-strings-xform.js:102:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Sandboxes\myproj\node_modules\underscore\underscore.js:78:11)
    at utils.inherits.write (C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xform\shared-strings-xform.js:101:7)
    at BaseXform.toXml (C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xform\base-xform.js:71:10)
    at xml (C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xform\base-xform.js:66:17)
    at C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xlsx.js:698:39
    at Promise._execute (C:\Sandboxes\myproj\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (C:\Sandboxes\myproj\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (C:\Sandboxes\myproj\node_modules\bluebird\js\release\promise.js:77:14)
    at Object.XLSX.addSharedStrings (C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xlsx.js:697:14)
    at C:\Sandboxes\myproj\node_modules\exceljs\lib\xlsx\xlsx.js:942:16
    at tryCatcher (C:\Sandboxes\myproj\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Sandboxes\myproj\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Sandboxes\myproj\node_modules\bluebird\js\release\promise.js:559:18)
```

**Comment by vfro** [comment]
It happens if I call ```worksheet.addRow``` with empty string as a named column's value, for example:
```javascript
worksheet.addRow({
   myColumn: ''
});
```

**Comment by jaykhengar** [comment]
I had same issue, that we have solved with handling undefined in "shared-string-xform.js" (lib/xlsx/xform/shared-string-xform.js).

I have changed the below line (Line 56):
if (model.richText) {

with:
if (model != undefined && model.richText) {

and it worked for me.

Please try to consider this issue in next release :)

**Comment by james075** [comment]
I can fix and PR it if you want ?

**Comment by euqen** [comment]
This bug is actual for versions higher than ``0.2.4``.

**Comment by DigitalSolomon** [comment]
I ran into this issue as well. Node v5.9.1, exceljs v0.2.8 :

`Unhandled rejection TypeError: Cannot read property 'richText' of undefined
    at utils.inherits.write (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xform/shared-string-xform.js:56:14)
    at /Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xform/shared-strings-xform.js:102:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/underscore/underscore.js:78:11)
    at utils.inherits.write (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xform/shared-strings-xform.js:101:7)
    at BaseXform.toXml (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xform/base-xform.js:71:10)
    at xml (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xform/base-xform.js:66:17)
    at /Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xlsx.js:698:39
    at Promise._execute (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.XLSX.addSharedStrings (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xlsx.js:697:14)
    at /Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/exceljs/lib/xlsx/xlsx.js:942:16
    at tryCatcher (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Applications/MAMP/htdocs/TruBeauty/tools/sdserver/node_modules/bluebird/js/release/promise.js:559:18)`

**Comment by psalmody** [comment]
+1 issue in Node v5.4.1 and exceljs 0.2.7

**Comment by james075** [comment]
Fixed in this PR #121

**Comment by barbalex** [comment]
+1 this error is blocking the delivery of my application :-(

**Comment by DigitalSolomon** [comment]
I had to bail on this library entirely unfortunately and go back to
PHPExcel and then interface that with my Node.js via HTTP. Not ideal, but
ran into too many issues with exceljs.

On Mon, Jun 20, 2016 at 3:35 AM, Alexander Gabriel <notifications@github.com
> wrote:

> +1 this error is blocking the delivery of my application :-(
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/guyonroche/exceljs/issues/120#issuecomment-227107424>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGcp4mpCb9yvwcV0TCQwbcNxlEG0TeVzks5qNmzngaJpZM4IgcEb>
> .
>



-- 
J T F

**Comment by vfro** [comment]
James, when the fix is going to be published as a part of new release on npm?

**Comment by barbalex** [comment]
This is biting us again 6 years later with version 4.3.0 😢

**Comment by barbalex** [comment]
Got it: it happened because we accidentally passed a function instead of a value.

**Comment by vaynevayne** [comment]
> This is biting us again 6 years later with version 4.3.0 😢

same

**Comment by jianjimi** [comment]
> 6 年后，4.3.0 版本再次困扰着我们 😢

依旧困扰
