### ISSUE TITLE
Unhandled rejection Error: Out of bounds. Invalid column letter: 

### ISSUE THREAD

**Issue by vanchisel** [guyonroche/exceljs#134]
I'm attempting to read an excel xslx with a drop down column with options as the image shows. 
![excelcolumn](https://cloud.githubusercontent.com/assets/10993089/15981104/035bb23e-2f3f-11e6-9d42-b616f726c888.jpg)

`js-xlsx` doesn't seem a versatile as `exceljs`, except I cannot read this file. It's a file my company uses nationally and would like read and edited through automation.

The error I am getting is 

```
Unhandled rejection Error: Out of bounds. Invalid column letter: MONTH
    at Object.l2n (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\utils\col-cache.js:78:13)
    at Object.decodeAddress (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\utils\col-cache.js:112:26)
    at Object.decodeEx (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\utils\col-cache.js:179:21)
    at Object.addCell (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\utils\cell-matrix.js:36:29)
    at C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\doc\defined-names.js:176:16
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Thomas\electron\eqs\node_modules\underscore\underscore.js:78:11)
    at C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\doc\defined-names.js:175:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Thomas\electron\eqs\node_modules\underscore\underscore.js:78:11)
    at Object.set model [as model] (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\doc\defined-names.js:173:7)
    at Object.set model [as model] (C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\doc\workbook.js:146:30)
    at C:\Users\Thomas\electron\eqs\node_modules\exceljs\lib\xlsx\xlsx.js:579:31
    at tryCatcher (C:\Users\Thomas\electron\eqs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Thomas\electron\eqs\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\Thomas\electron\eqs\node_modules\bluebird\js\release\promise.js:559:18)
```
Line 78 of col-cache.js is: 
```
 if (!this._l2n[l]) {
      throw new Error('Out of bounds. Invalid column letter: ' + l);
 }
```

So the problem is with the columns because simplier xlsx files are read.

Does anyone have a clue how I can fix or bypass this? If I was writing, as @jozsi and @barbalex, that solution would work. Any help? Thanks in advance.

**Comment by psalmody** [comment]
I think #159 is symptom of this issue. I get this same error with invalid column letter: REPT.

My mock data for testing is: 
[DB_TEST.MOCK_DATA.xlsx](https://github.com/guyonroche/exceljs/files/402867/DB_TEST.MOCK_DATA.xlsx)

![image](https://cloud.githubusercontent.com/assets/12420157/17421173/49214f8c-5a54-11e6-8f73-8788d0401ab8.png)


I threw a `console.log` at `lib/utils/col-cache` before the error throw (line 78) and noticed it was looping through all the columns. Interesting, it went all the way to XFD which is the last column Excel will show me in the spreadsheet. THEN it throws the error. 

Javascript used to generate this error:

```js
var filename = '...';
var Excel = require('c:/www/exceljs');
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(filename).then(function() {
  worksheet = workbook.getWorksheet(1);
});
```

Full trace:

```
Unhandled rejection Error: Out of bounds. Invalid column letter: REPT
    at Object.module.exports.l2n (c:\www\exceljs\lib\utils\col-cache.js:79:13)
    at Object.module.exports.decodeAddress (c:\www\exceljs\lib\utils\col-cache.js:113:26)
    at Object.module.exports.decodeEx (c:\www\exceljs\lib\utils\col-cache.js:198:26)
    at Object.CellMatrix.addCell (c:\www\exceljs\lib\utils\cell-matrix.js:36:29)
    at c:\www\exceljs\lib\doc\defined-names.js:176:16
    at Array.forEach (native)
    at Function._.each._.forEach (c:\www\exceljs\node_modules\underscore\underscore.js:78:11)
    at c:\www\exceljs\lib\doc\defined-names.js:175:9
    at Array.forEach (native)
    at Function._.each._.forEach (c:\www\exceljs\node_modules\underscore\underscore.js:78:11)
    at Object.model (c:\www\exceljs\lib\doc\defined-names.js:173:7)
    at Object.model (c:\www\exceljs\lib\doc\workbook.js:166:30)
    at c:\www\exceljs\lib\xlsx\xlsx.js:201:31
From previous event:
    at Parse.<anonymous> (c:\www\exceljs\lib\xlsx\xlsx.js:197:10)
    at emitNone (events.js:72:20)
    at Parse.emit (events.js:166:7)
    at Parse._flush (c:\www\exceljs\node_modules\unzip2\lib\parse.js:319:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by vanchisel** [comment]
My project called for reading/writing to various .xlsx files with multiple sheets without needing to open or change the format or formulas. Because I couldn't solve this issue with exceljs I ended up writing my spreadsheet handling in c# with [Spreadsheetlight](http://spreadsheetlight.com/) (creating a .dll and .exe separately). I used the .exe as there was an exception thrown that .dll couldn't handle.

I use [node child_process](https://nodejs.org/api/child_process.html) in my electron app to run the processeses by calling and passing the json object data to the .dll, but with the .exe I passed the json file via command line argument.

The procedures are working flawlessly with Spreadsheetlight.

**Comment by pwillart** [comment]
An easy workaround is to set the column property for the worksheet. I ran into a similar issue when using getColumn with index. After setting worksheet.columns I could access them by key.
Something like this:
```
    worksheet.columns = [
      { header: 'Category', key: 'category'},
      { header: 'Name', key: 'name'},
      { header: 'Key', key: 'key'},
      { header: 'Value', key: 'value'}
    ];
```
