### ISSUE TITLE
crash on fresh install

### ISSUE THREAD

**Issue by gaburibe** [guyonroche/exceljs#309]
Hello i just installed exceljs but it crashes, i haven't put any code in it just the require and the next error log comes out:

readxls/node_modules/exceljs/lib/doc/worksheet.js:455
    var { top, left, bottom, right } = decoded;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/imac/Sites/readxls/node_modules/exceljs/lib/doc/workbook.js:25:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by guyon-elsevier** [comment]
Which version of NodeJS are you using?

**Comment by guyonroche** [comment]
Which version of NodeJS are you using?

**Comment by lukealbao** [comment]
Yeah, having the same. Can you please add an engines entry to the package.json? Running on node 4.4.6 and exceljs 0.4.4. According to http://node.green/, it will need to be at least Node v6.4.0 for the destructuring assignment.

Note, this probably should be in documentation, too, as I'm not sure how you would re-release 0.4.4 with the engines flag. Thank you!

**Comment by gaburibe** [comment]
Mine is 4.4.7, I downloaded the previous version of exceljs and it works just fine. Good work by the way

**Comment by guyonroche** [comment]
ok - my apologies for that.
I'll work back to 4.0.0 compatability as soon as I can.
After that, I think I'm going to need a dist folder
