### ISSUE TITLE
class Promish extends Base Error

### ISSUE THREAD

**Issue by PaolaGarcia** [guyonroche/exceljs#321]
I have a program that uses exceljs. But when I install npm install exceljs and try to run my code I get the following error:

node_modules/exceljs/node_modules/promish/lib/promish-class.js:13
  class Promish extends Base {
  ^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/webapps/teletemp_proy/teletempv2/node_modules/exceljs/node_modules/promish/lib/promish.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

My code is like this:

`var Excel = require('exceljs');
var workbook = new Excel.Workbook();

workbook.xlsx.readFile('Document.xlsx')
	.then(function() {
                var worksheet_content = workbook.getWorksheet("Sheet 1");
                var row = worksheet_content.getRow(2);
		row.getCell(2).value = "Test"; 
		row.commit();
                return workbook.xlsx.writeFile('Test.xlsx');
       });
`

I can't find any solution to my problem

**Comment by idzer0lis** [comment]
Before ES6, the 'class' keyword was a reserved word. Check if ES6 is added/configured correctly in your system/environment.
