### ISSUE TITLE
Error reading xls

### ISSUE THREAD

**Issue by argordmel** [guyonroche/exceljs#429]
Hello

I'm getting this error when I try to read a file:

TypeError: the promise constructor cannot be invoked directly

    See http://goo.gl/MqrFmX

    at Promish (/folder/node_modules/promish/lib/promish-class.js:23:9)
    at Object.exists (/folder/node_modules/exceljs/dist/es5/utils/utils.js:136:14)
    at Object.readFile (folder/node_modules/exceljs/dist/es5/xlsx/xlsx.js:57:21)

This is my code:
```javascript
const workbook = new Excel.Workbook();
return workbook.xlsx.readFile('./test.xlsx').then( () => { 
 // TODO
});
```
MacOS
exceljs: 0.6.29
node: 6.11.5

Note: With exceljs@0.2.39 works fine (with some warnings)

Thanks!

**Comment by mfahmirukman** [comment]
I believe you dont need to use the first return `return workbook.xlsx.readFile('./test.xlsx')`

**Comment by argordmel** [comment]
The warnings were silenced with this:

```javascript
const ExcelJS = require('exceljs');
ExcelJS.config.setValue('promise', require('bluebird');
```

Thanks!
