### ISSUE TITLE
"Cannot read property 'length' of null" When calling addRow() on a Streaming workbook

### ISSUE THREAD

**Issue by zgriesinger** [guyonroche/exceljs#444]
First off, as usual, great library, it is extremely powerful and easy to use

I've just been scratching my head in relation to a certain error I've been getting.

So the script I have downloads a zip file from an FTP server streams the output to an unzip library that outputs a stream for each entry in the zip file. For each of these entry streams I take each line and add it to a streaming workbook and commit the line. However when I try to write the parsed CSV array I am getting an Error in worksheet-writer.js that is as follows:
```
TypeError: Cannot read property 'length' of null
worksheet-writer.js:299
    at module.exports.get _nextRow [as _nextRow] (c:\automation-catalog\node_modules\exceljs\dist\es5\stream\xlsx\worksheet-writer.js:302:38)
    at module.exports.addRow (c:\automation-catalog\node_modules\exceljs\dist\es5\stream\xlsx\worksheet-writer.js:368:33)
    at ParserStream.<anonymous> (c:\automation-catalog\scripts\test.js:176:43)
    at emitOne (events.js:115:13)
    at ParserStream.emit (events.js:210:7)
    at spreadArgs (c:\automation-catalog\node_modules\fast-csv\lib\extended.js:43:25)
    at ParserStream.emit (c:\automation-catalog\node_modules\fast-csv\lib\parser\parser_stream.js:325:13)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at ParserStream.Readable.push (_stream_readable.js:211:10) 
```

Here is the code snippet:
``` 
var opts = {
            filename: './test.xlsx',
            useStyles: true,
            useSharedStrings: true
        };
var workbook = new Excel.stream.xlsx.WorkbookWriter(opts);
var entryNum = 1;
sftp.connect(sftpConfig).then(() => {
    return sftp.list('./')
}).then((data) => {
    return sftp.get(zipName, true, null);
}).then((data) => {
    const reader = data;
    reader.pipe(unzip.Parse())
    .on('entry', function(entry) {
        var sheet = workbook.addWorksheet("Sheet" + entryNum);
        entryNum += 1
        var delimiter = "";
        if(entry.type === "File") {
            entry.pipe(es.split())
            .on('data', function(chunk) {
                if(delimiter === "") {
                    if(chunk.indexOf('\t') !== -1)
                        delimiter = "\t"
                    else if(chunk.indexOf(",") !== -1)
                        delimiter = ","
                } else {
                    csv.fromString(chunk, {delimiter: delimiter})
                    .on("data", function(data) {
                        if(false) {
                            var cols = []
                            for(var j = 0; j < data.length; j++ ){
                                cols.push({
                                    width: 30.78
                                })
                            }
                            sheet.addRow(data).commit();
                            first = false
                        } else {
                            sheet.addRow(data).commit()
                        }
                    })
                }
            })
        .on('end', function() {
            sheet.commit();
        })
        }
    });
     reader.on('end', function() {
            workbook.commit().then(function() {
                console.log("DONE!")
            })
    })
})
```
I can assure that the file is being returned and that the data variable passed to addRow() is an array of strings

**Comment by zgriesinger** [comment]
I was able to figure it out, I was committing the entire workbook before all the rows were written because I was listening to the end of the wrong stream.
