### ISSUE TITLE
App crashed after stream closed.

### ISSUE THREAD

**Issue by safonovklim** [guyonroche/exceljs#500]
Node: v8.9.4 (**no bug on node v6.***)
NPM: 5.6.0
Koa: v1.2.4/v2.5.0

_Note: `ctx` already defined by Koa_
```
import { Client } from 'pg';
import PgQueryStream from 'pg-query-stream';
import config from '../../config';

const pgDirectClient = new Client({
  user: config.db.username,
  host: config.db.host,
  database: config.db.databaseName,
  password: config.db.password,
  port: config.db.port,
});
pgDirectClient.connect();

const sqlQueryStream = pgDirectClient.query(new PgQueryStream("SELECT * FROM users"));
const fileFormat = 'xlsx';
const formatRow = row => [row.id, row.name];
const closeStream = ctx.end;
const sheetName = 'Sheet_1';
const headFields = ['id', 'name'];
const workbook = new exceljs.stream.xlsx.WorkbookWriter({
  stream: ctx.body,
  useStyles: false,
  useSharedStrings: false,
});

const sheet = workbook.addWorksheet(sheetName);
sheet.addRow(headFields).commit();

sqlQueryStream
      .on('data', (data) => {
        sheet.addRow(formatRow(data)).commit();
      });

sqlQueryStream
  .on('end', () => {
    workbook.commit().then(() => closeStream());
  });
```

OR 

```
...
sqlQueryStream
  .on('end', () => {
    workbook.commit();
  });
```
+ Added `console.log` to all `.on` listeners for debug purpose.

Logs

```
npm run..server sqlQueryStream.on(data) (data.id=149)
npm run..server sqlQueryStream.on(end)
npm run..server workbook.stream.on('finish')
npm run..server TypeError: Cannot read property 'objectMode' of undefined
npm run..server     at module.exports.Readable.push (_stream_readable.js:195:14)
npm run..server     at module.exports.Duplex._destroy (_stream_duplex.js:104:8)
npm run..server     at module.exports.destroy (internal/streams/destroy.js:32:8)
npm run..server     at destroy (/usr/src/app/node_modules/destroy/index.js:41:12)
npm run..server     at listener (/usr/src/app/node_modules/on-finished/index.js:169:15)
npm run..server     at onFinish (/usr/src/app/node_modules/on-finished/index.js:100:5)
npm run..server     at callback (/usr/src/app/node_modules/ee-first/index.js:55:10)
npm run..server     at ServerResponse.onevent (/usr/src/app/node_modules/ee-first/index.js:93:5)
npm run..server     at emitNone (events.js:111:20)
npm run..server     at ServerResponse.emit (events.js:208:7)
npm run..server     at onFinish (_http_outgoing.js:723:10)
npm run..server     at afterWrite (_stream_writable.js:454:3)
npm run..server     at _combinedTickCallback (internal/process/next_tick.js:144:20)
npm run..server     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

No results after research in exceljs issues, node issues, google and stackoverflow :(

**Comment by safonovklim** [comment]
Also:
* File downloaded successfully with correct content.

**Comment by rnzo** [comment]
Hello, did you find any solution to this? I'm having the same problem

**Comment by safonovklim** [comment]
I've created demo app: https://github.com/safonovklim/exceljs-issue-500-demo

Also checkout branch `no-issue-node6` (difference - only changed node version to 6.* latest)

**Comment by khawkinson** [comment]
@safonovklim I use koa and struggled with this for awhile also and this worked for me:
```javascript
const stream = new Stream.PassThrough();
const workbook = new Excel.stream.xlsx.WorkbookWriter({ stream });
 // do all you want to the workbook
ctx.body = stream;
```

**Comment by safonovklim** [comment]
Hi there.

I've fixed this issue by adding Transform stream into WorkbookWriter (and assigning to ctx.body/this.body)

```
const resStream = new Transform();
    resStream._transform = function handleTransform(data, encoding, done) {
      this.push(data);
      done();
    };
```
