### ISSUE TITLE
Error trying to read xlsx from stream

### ISSUE THREAD

**Issue by tamethecomplex** [guyonroche/exceljs#539]
Hi,

First off, thanks for this great package!

When I try to read from a buffer and write to a stream obtained through workbook.xlsx.createInputStream, I get the same error reported at https://github.com/guyonroche/exceljs/issues/311 for reading files.  What is wrong with the below?

```
const workbook = new Excel.Workbook()
const buffer = Buffer.from(fileBuffer)
const readStream = new stream.PassThrough()
const writeStream = workbook.xlsx.createInputStream()
readStream.end(buffer)
readStream.pipe(writeStream)

writeStream.on('finish', () => {
  resolve(workbook)
})

readStream.on('end', () => {
  writeStream.end()
})

readStream.on('data', chunk => {
  writeStream.write(chunk)
})
```

**Comment by guyonroche** [comment]
@tamethecomplex  it's likely that while the stream has reached the end (or finish, etc) that there is more work that ExcelJS needs to do.
ExcelJS will emit ('done') on the stream when it has completed its processing
could you try:
```
writeStream.on('done', () => {
  resolve(workbook)
});

**Comment by mihaidma** [comment]
This doesn't work for me either. The proposed solution does not seem to work, the 'done' is not called.

Only worked when I used
```
workbook.xlsx.read(readStream).then((wrk)=> {
  // valid wrk
})
```

**Comment by BenjaminDish** [comment]
Hello,

I'm trying to load a xlsx file into a workbook using this piece of code. It seems to be a good way but I get an error.
Actually I'm just using @tamethecomplex's code trying to correct it using @guyonroche's comment, wrapping it into a promise..

Here is my code :

```
public static async getWorkbookFromBuffer(buffer: Buffer): Promise<any> {
        return new Promise((resolve, reject) => {
            try {
                const workbook = new Excel.Workbook();
                const readStream = new stream.PassThrough();
                const writeStream = workbook.xlsx.createInputStream();
                readStream.end(buffer);
                readStream.pipe(writeStream);

                writeStream.on('done', () => {
                    resolve(workbook)
                })

                readStream.on('end', () => {
                    writeStream.end()
                })

                readStream.on('data', chunk => {
                    writeStream.write(chunk)
                })
            }
            catch (e) {
                reject(e);
            }
        });
    }
```

When using this method, I get an error : 

```
Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex ({myPath}\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset ({myPath}\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData ({myPath}\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString ({myPath}\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature ({myPath}\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral ({myPath}\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load ({myPath}\node_modules\jszip\lib\zipEntries.js:256:14)
    at {myPath}\node_modules\jszip\lib\load.js:49:20
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Any idea about what make me run into this ?
Thanks
